2 add harpgl support
GeospatialResearch/gri-earthquake pull request #7
Opened 2021-07-15 01:27 UTC by LukeParky

Adds the Harp.GL mapping library to the project.
By following the README contributors should be able to have a map shown on the application.

2021-07-15 03:14 UTC, rosepearson commented
Good clear readme instructions and clear overall directory and file structure. 👍

2021-07-15 23:26 UTC, rosepearson commented
The code changes look good to me. I've going to have a look through some of the associated files - i.e. from previous commits prior to the PR, before finishing up.

2021-07-15 23:41 UTC, rosepearson requested changes
I've mainly suggested the addition of a few comments and details to the read me. From my perspective the minimum is to add docstrings to app.py. 

Does it make sense to add some basic tests to the server and client?

Let me now when you've made the changes you decide to make and I'll take another look! :)

2021-07-15 23:41 UTC, rosepearson commented on README.md
> +   [Here API Freemium Project](https://developer.here.com/projects).
This can be created for free by first creating *an account at* [Here API Freemium Project](https://developer.here.com/projects).

2021-07-15 23:41 UTC, rosepearson commented on README.md
> +   After this you must retrieve a [Here XYZ API Access Management Token](https://xyz.api.here.com/token-ui/accessmgmt.html).
After this you must retrieve a [Here XYZ API Access Management Token](https://xyz.api.here.com/token-ui/accessmgmt.html) *by selecting 'Generate Token' under the 'Access Management' tab and selecting all check-boxes".

2021-07-15 23:41 UTC, rosepearson commented on README.md
> +* [Here API Freemium Project](https://developer.here.com/projects) (Project Registration for API for OSM tile data for harp.gl)
As far as I can see the top three need to be installed in the environment and the bottom two are more about having a login and setting up your token/credentials. I wonder if its worth splitting these out and providing a conda example for the top three. It really depends on your target audience but some people might not realise they need to install pip, and npm - and get stuck. :)

2021-07-15 23:53 UTC, LukeParky commented on README.md
> +* [Here API Freemium Project](https://developer.here.com/projects) (Project Registration for API for OSM tile data for harp.gl)
Yup thats a good point. I'm not currently using conda for this application but I will make sure to add extra instructions for that

2021-07-16 00:05 UTC, LukeParky commented
Still to do for this PR:
* Make nested README structure or additional .md files for instructions
* Increase in-code documentation
* Add screenshots to the README
* Update AboutPage to github
* Resolve comments

2021-07-19 03:51 UTC, rosepearson approved these changes
Hi @LukeParky, your changes look good to me. I like the comments and child readme's. It's made everything a lot clearer to me. Nice work.

The only think I notice is a few warnings about files ending without a new line i.e. client/decoders/harp-gl-decoder.config.js - but i'll leave that to your discretion if you address this now or not.

2021-07-19 03:51 UTC, rosepearson commented on README.md
> +
Cool! Thanks for the screenshot and details.

2021-07-19 03:51 UTC, rosepearson commented on README.md
> +
Nice - much clearer.

2021-07-19 03:51 UTC, rosepearson commented on README.md
> +
Nice - again very clear.

2021-07-19 03:51 UTC, rosepearson commented on README.md
> +
Nice reference to the relevant issue.

2021-07-19 03:51 UTC, rosepearson commented on README.md
> +└───client # files used in the client-side application, run in the user's browser
I like how you've illustrated the folder structure - both her and in the child readme's.

2021-07-19 03:51 UTC, rosepearson commented on client/README.md
> +    |   # Source code for the client module. Includes entry point main.js and other source files
I really like these descriptions. This was very clarifying for me.

2021-07-19 03:51 UTC, rosepearson commented on client/src/requests.js
Nice comment and renamed variables are clearer

2021-07-19 03:57 UTC, LukeParky commented
> Hi @LukeParky, your changes look good to me. I like the comments and child readme's. It's made everything a lot clearer to me. Nice work.
> 
> The only think I notice is a few warnings about files ending without a new line i.e. client/decoders/harp-gl-decoder.config.js - but i'll leave that to your discretion if you address this now or not.

Thanks Rose, I'll make those changes and merge

2021-07-19 04:06 UTC, merged